# Generated by Django 3.0.3 on 2020-02-22 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200217_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.URLField(),
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image_service', to='api.File')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_image', to='api.Service')),
            ],
        ),
    ]
