# Generated by Django 3.0.3 on 2020-05-07 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200222_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interests',
            name='interest',
            field=models.CharField(choices=[('1', 'EXEMPLO1'), ('2', 'EXEMPLO2'), ('3', 'EXEMPLO3'), ('4', 'OTHER')], max_length=2),
        ),
        migrations.AlterField(
            model_name='interests',
            name='other',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='interests',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='api.Person'),
        ),
    ]
