# Generated by Django 3.0.3 on 2020-06-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200509_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='telephone',
            field=models.CharField(max_length=11),
        ),
    ]
