# Generated by Django 3.0.3 on 2020-06-25 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200625_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='whatsapp',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
