# Generated by Django 3.0.3 on 2020-06-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200625_2347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hiredservice',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='hiredservice',
            name='accepted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='hiredservice',
            name='finished_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='interests',
            name='interest',
            field=models.CharField(choices=[('1', 'EXEMPLO1'), ('2', 'EXEMPLO2'), ('3', 'EXEMPLO3'), ('0', 'OTHER')], max_length=2),
        ),
    ]
